version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing dependencies
      - sudo apt-get update -y
      - sudo apt-get install -y zip unzip

  pre_build:
    commands:
      - echo Installing Composer
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  build:
    commands:
      - echo Build started on `date`
      - echo Installing PHP dependencies
      - composer install --no-interaction --prefer-dist
      - mv .env.example .env
      - php artisan key:generate

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifact
      - rm -rf "*.git*"

artifacts:
  files:
    - '**/*'
